# Generated by Django 6.0.5 on 2026-05-29 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='시리즈명')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='슬러그')),
                ('description', models.TextField(blank=True, verbose_name='시리즈 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '시리즈',
                'verbose_name_plural': '시리즈 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='슬러그')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('summary', models.TextField(blank=True, verbose_name='요약글(설명)')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사용자 목록')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.series', verbose_name='시리즈')),
            ],
            options={
                'verbose_name': '블로그 게시글',
                'verbose_name_plural': '블로그 게시글 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
