# Generated by Django 6.0.5 on 2026-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('education', '교육수료/학력'), ('experience', '경력/프로젝트'), ('award', '수상/대회'), ('certificate', '자격증'), ('thesis', '논문/연구')], max_length=20, verbose_name='섹션 종류')),
                ('title', models.CharField(max_length=200, verbose_name='제목 (예: 학교명, 회사명, 대회명)')),
                ('sub_title', models.CharField(blank=True, max_length=200, verbose_name='부제목/기간/소속')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '포트폴리오 항목',
                'verbose_name_plural': '포트폴리오 항목 목록',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('title', models.CharField(default='보안을 고려한 창의적인 개발자', max_length=200, verbose_name='한 줄 소개')),
                ('skills', models.CharField(default='Django, Python, HTMX, Alpine.js, CSS', max_length=500, verbose_name='기술 스택 (쉼표로 구분)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='portfolio/profile/', verbose_name='프로필 이미지')),
            ],
            options={
                'verbose_name': '포트폴리오 프로필',
                'verbose_name_plural': '포트폴리오 프로필',
            },
        ),
    ]
